# Generated by Django 2.2.5 on 2019-10-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
